services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .docker.env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./server/uploads:/app/server/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your-secure-mysql-password-change-this
      MYSQL_DATABASE: pasarantar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    restart: unless-stopped

volumes:
  db_data:

networks:
  app-network:
    driver: bridge